---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli

inputs:
  - name: compiled-site

run:
  path: bash
  args:
    - "-c"
    - "cd ./compiled-site && cf login --sso-passcode ((tas_passcode)) -a https://api.run.pcfone.io -o pivot-ikanshyn -s dev && cf push -f manifest.yml"
